
VI_ST_ITEM( VI_TYPE_UNKNOWN,    0, void,   "",  0 )
VI_ST_ITEM( VI_TYPE_BYTE,       1, u8,     "B", 8*sizeof(u8) )
VI_ST_ITEM( VI_TYPE_CHAR,       2, char,   "C", 8*sizeof(char) )
VI_ST_ITEM( VI_TYPE_INTEGER,    3, int,    "I", 8*sizeof(int) )
VI_ST_ITEM( VI_TYPE_BOOLEAN,    4, bool,   "b", 1 )
VI_ST_ITEM( VI_TYPE_INTEGER64,  5, s64,    "L", 8*sizeof(s64) )
VI_ST_ITEM( VI_TYPE_FLOAT,      6, double, "F", 8*sizeof(double) )
